### ISSUE TITLE
Prove property 2

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/fldgen#10]
Prove that within a single run the autocorrelation function for a grid cell is equal to that of the corresponding cell in the reference data.

This is guaranteed for the basis functions by the Wiener-Khinchin theorem.  We need to show that applying the W-K theorem to each basis function independently produces the appropriate ACF for each grid cell individually.

**Comment by abigailsnyder** [comment]
I think I have this one sketched on paper, I just need to work it out fully and then this weekend I'm going to take the time to properly setup the appendix in terms of lemmas and theorems so that we can clearly see what we have and what's missing

**Comment by abigailsnyder** [comment]
I think I have this sketched out on paper. I need to go through the full details to be sure. This weekend, I'm going to take the time to typeset the appendix properly with lemmas and then the properties, so it's easier to see what parts we have and what part we need.
