### ISSUE TITLE
Prove property 3

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/fldgen#11]
Prove that the spatial correlation in the generated fields is the same as the spatial correlation function for the input data.

We have a little flexibility in how we go about this.  Actually computing the spherical ACF is a pain, but we might be able to finesse that because we don't actually need to compute the ACF to prove that the ACFs for the two fields are equal.  Alternatively, it might be sufficient to show that the covariance matrices for the two fields are the same.

**Comment by abigailsnyder** [comment]
sketched this one out too; there's a couple things I need to clarify but so far, I believe there's no new conditions that will come from this. ie, once we have a method that satisfies property 1a, I think we have everything we need for this.
