### ISSUE TITLE
Test installing from github

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/fldgen#17]
Make sure that the fldgen v2 release candidate installs cleanly with `install_github`.  I always install from a local repository, so I don't think I've ever tried it.

**Comment by abigailsnyder** [comment]
same, I'll check it when I need a break this afternoon

**Comment by rplzzz** [comment]
Excellent.  I assigned us both, figuring that whoever got to it first would do it.

**Comment by abigailsnyder** [comment]
`devtools::install_github('JGCRI/fldgen', ref='v1.0.0', build_vignettes=TRUE)` works fine

`devtools::install_github('JGCRI/fldgen', ref='v2.0.0', build_vignettes=TRUE)` obviously fails:

```
Error: HTTP error 422.
  No commit found for SHA: v2.0.0
```

**Comment by rplzzz** [comment]
Makes sense.  We should try replacing 'v2.0.0' with the name of the branch with the release candidate. (`fldgen-v2-rc`).

**Comment by abigailsnyder** [comment]
fair point, that seems to work fine as well. RE the paper, the command with `v2.0.0` is what I have listed to install, thinking we'll ge it merged in and labeled by submission. Should I hedge my bets and replace with `fldgen-v2-rc`?

**Comment by rplzzz** [comment]
Good to know.  Thanks for checking into it.  Fun fact, hector won't install from within Rstudio with install_github (you can do it from a command-line R instance, and thereafter it works in Rstudio).  I wanted to make sure we didn't have any such issues here.

We definitely want the ref in the paper to be a tag and not a branch.  What do you think of `v2.0.0-pre`, with `v2.0.0` reserved for the version that has all the references fixed up.  Also, should we mention that `install_github('JGCRI/fldgen')` always gets you the latest stable version?

**Comment by abigailsnyder** [comment]
> We definitely want the ref in the paper to be a tag and not a branch. What do you think of v2.0.0-pre, with v2.0.0 reserved for the version that has all the references fixed up. Also, should we mention that install_github('JGCRI/fldgen') always gets you the latest stable version?


Yeah that works for me, will do
