### ISSUE TITLE
Create and archive trained emulators for popular ESMs

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/fldgen#27]
The hardest part of training an emulator is getting hold of the ESM data in the first place.  We should train joint temperature-precipitation emulators for all of the more well-known models in the ensemble.  We can archive those and provide functions to download them from the archive, saving most users the hassle of wrangling the raw ESM data.

**Comment by rplzzz** [comment]
We need to do this for the ISIMIP datasets, so that seems a good place to start.

**Comment by abigailsnyder** [comment]
redundant with https://github.com/JGCRI/fldgen/issues/15
