### ISSUE TITLE
Prove property 1A

### ISSUE THREAD

**Issue by rplzzz** [JGCRI/fldgen#8]
Prove that the variance of a grid cell in generated data is equal to the variance of the same cell in the input data.

**Comment by abigailsnyder** [comment]
Done up to needing to be tweaked following the switch to 2d transformation. And assuming $cov_t(\phi_{it}^\star, \phi_{jt}^\star) = 0$ for i != j .
Note that, to use Parseval's Theorem, we do now have an extra condition on the means of phi and phi*.

**Comment by abigailsnyder** [comment]
Oh and also assuming I didn't make a mistake applying Parseval's theorem or elsewhere. The Parseval's theorem especially, I could see myself misunderstanding subscripts. It's also been a minimum of 4 years since I had to use that theorem. And even then, it was only the continuous version

**Comment by rplzzz** [comment]
We should talk more about this one, then.
